// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MyMvcApp.Data;

#nullable disable

namespace MyMvcApp.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260330105525_SeedTestData")]
    partial class SeedTestData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .UseCollation("Latin1_General_100_CI_AS_SC_UTF8")
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "2",
                            Name = "Dentist",
                            NormalizedName = "DENTIST"
                        },
                        new
                        {
                            Id = "3",
                            Name = "Staff",
                            NormalizedName = "STAFF"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "1",
                            RoleId = "1"
                        },
                        new
                        {
                            UserId = "2",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "3",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "4",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "5",
                            RoleId = "2"
                        },
                        new
                        {
                            UserId = "6",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "7",
                            RoleId = "3"
                        },
                        new
                        {
                            UserId = "8",
                            RoleId = "3"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", (string)null);
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.Activity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Time")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Activities");
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "1",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "6e75ce2f-6f53-4402-b955-9fbe6c3678e4",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 23, 830, DateTimeKind.Local).AddTicks(3555),
                            DateOfBirth = new DateOnly(1990, 1, 1),
                            Email = "admin@dental.com",
                            EmailConfirmed = true,
                            FullName = "System Administrator",
                            Gender = "Male",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@DENTAL.COM",
                            NormalizedUserName = "ADMIN@DENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBFJ7s0dkRl028F8JbAIIWdLnMpsFZXNZu7WzFymlEM9CuDbRQJdkssTcHzEXvy5Dg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "29a6b1cf-aea8-4768-b2a1-25b0cdb2d42b",
                            TwoFactorEnabled = false,
                            UserName = "admin@dental.com"
                        },
                        new
                        {
                            Id = "2",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "26b0fc42-5498-46fe-83d7-95266defb013",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 23, 891, DateTimeKind.Local).AddTicks(2269),
                            DateOfBirth = new DateOnly(1985, 5, 15),
                            Email = "dentist1@dental.com",
                            EmailConfirmed = true,
                            FullName = "Dr. Nguyễn Văn A",
                            Gender = "Male",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DENTIST1@DENTAL.COM",
                            NormalizedUserName = "DENTIST1@DENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBVDpIZD+qW6iNblfHAVt6/3v8rNK+MZb3Sa/7zLAmv7WCbzeMHJ/oEoL75DPFgpBQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "41c1e52b-c689-4585-9f24-982aa5488dfe",
                            TwoFactorEnabled = false,
                            UserName = "dentist1@dental.com"
                        },
                        new
                        {
                            Id = "3",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "b2680803-3bfc-425e-9446-27d7e8f04c61",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 23, 953, DateTimeKind.Local).AddTicks(475),
                            DateOfBirth = new DateOnly(1987, 3, 20),
                            Email = "dentist2@dental.com",
                            EmailConfirmed = true,
                            FullName = "Dr. Trần Thị B",
                            Gender = "Female",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DENTIST2@DENTAL.COM",
                            NormalizedUserName = "DENTIST2@DENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOynxcc36v90zg9yAP9jwgjTheZvdL8u8H0sSzK/z33rbax1UgApbhTJtU/wvKqPYw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "2130117b-ff53-48aa-a0e0-6c157d930645",
                            TwoFactorEnabled = false,
                            UserName = "dentist2@dental.com"
                        },
                        new
                        {
                            Id = "4",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "5678ebcd-b450-4b41-9079-e3fdad0049fd",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 14, DateTimeKind.Local).AddTicks(356),
                            DateOfBirth = new DateOnly(1989, 7, 10),
                            Email = "dentist3@dental.com",
                            EmailConfirmed = true,
                            FullName = "Dr. Lê Văn C",
                            Gender = "Male",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DENTIST3@DENTAL.COM",
                            NormalizedUserName = "DENTIST3@DENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGpn1rKbNl+uOFm89mzWy6Bs2OsiR9+gzY6MwOsXbxtLmzseFqjjJPfTKJkR2QF/Jw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "35750c52-3a24-4604-85fa-c92a7df69747",
                            TwoFactorEnabled = false,
                            UserName = "dentist3@dental.com"
                        },
                        new
                        {
                            Id = "5",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "91ac7091-f9b1-4cef-bcaa-43e7b4d35251",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 74, DateTimeKind.Local).AddTicks(6953),
                            DateOfBirth = new DateOnly(1991, 9, 25),
                            Email = "dentist4@dental.com",
                            EmailConfirmed = true,
                            FullName = "Dr. Phạm Thị D",
                            Gender = "Female",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "DENTIST4@DENTAL.COM",
                            NormalizedUserName = "DENTIST4@DENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENqAKaJ+C6c/R6uJomgENkl2DbsJcD33XfiUxhiqhgJq9A8pLDkEoNlLevSQWtOMlg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "aed411a5-e922-49d2-8254-c9e40e77aeb4",
                            TwoFactorEnabled = false,
                            UserName = "dentist4@dental.com"
                        },
                        new
                        {
                            Id = "6",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "9b8a5006-dad2-491d-82a9-983bb42cd9a4",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 135, DateTimeKind.Local).AddTicks(2615),
                            DateOfBirth = new DateOnly(1993, 2, 14),
                            Email = "staff1@dental.com",
                            EmailConfirmed = true,
                            FullName = "Nguyễn Thị E",
                            Gender = "Female",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF1@DENTAL.COM",
                            NormalizedUserName = "STAFF1@DENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAENFan8CLr0OEm040eiQW8sTXf+iLDp0w6qQcRGPMxf43xXfDiIezSLJ+CvoDAsw5Xw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "89ab51c2-f58e-4efb-ac43-b6874cbad826",
                            TwoFactorEnabled = false,
                            UserName = "staff1@dental.com"
                        },
                        new
                        {
                            Id = "7",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "e07a9e80-2914-4f97-b868-84ade49d4071",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 199, DateTimeKind.Local).AddTicks(1864),
                            DateOfBirth = new DateOnly(1994, 6, 8),
                            Email = "staff2@dental.com",
                            EmailConfirmed = true,
                            FullName = "Trần Văn F",
                            Gender = "Male",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF2@DENTAL.COM",
                            NormalizedUserName = "STAFF2@DENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEOI/q44is/xJ3QJ7LnLzS71rPPw+YY0G9e8WDwo7vucZXKNzhIE81uvkNMBW1pFXJA==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "13b3fb97-1ef5-49e1-a58f-02f43c020a44",
                            TwoFactorEnabled = false,
                            UserName = "staff2@dental.com"
                        },
                        new
                        {
                            Id = "8",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "43e4ecb6-01df-4695-b0a6-508346df6674",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 260, DateTimeKind.Local).AddTicks(7291),
                            DateOfBirth = new DateOnly(1995, 11, 30),
                            Email = "staff3@dental.com",
                            EmailConfirmed = true,
                            FullName = "Lê Thị G",
                            Gender = "Female",
                            IsActive = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "STAFF3@DENTAL.COM",
                            NormalizedUserName = "STAFF3@DENTAL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAELMIe00GWHfMEgOUvKA5n1+TcCl9rAKXUuoMBFg5x4TO3s0gqxP41W2Rga51XrMChg==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "239f0114-e496-4229-a897-6383c662bf0b",
                            TwoFactorEnabled = false,
                            UserName = "staff3@dental.com"
                        });
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.Appointment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("AppointmentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DentistId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<TimeSpan>("EndTime")
                        .HasColumnType("time");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("PatientName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("StartTime")
                        .HasColumnType("time");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("DentistId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Appointments");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AppointmentDate = new DateTime(2026, 3, 31, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1443),
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1473),
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DentistId = "2",
                            EndTime = new TimeSpan(0, 9, 30, 0, 0),
                            PatientId = 1,
                            PatientName = "Nguyễn Văn An",
                            ServiceId = 1,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 2,
                            AppointmentDate = new DateTime(2026, 3, 31, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1443),
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1476),
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DentistId = "3",
                            EndTime = new TimeSpan(0, 10, 45, 0, 0),
                            PatientId = 2,
                            PatientName = "Trần Thị Bích",
                            ServiceId = 2,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 3,
                            AppointmentDate = new DateTime(2026, 4, 1, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1443),
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1479),
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DentistId = "4",
                            EndTime = new TimeSpan(0, 11, 45, 0, 0),
                            PatientId = 3,
                            PatientName = "Lê Văn Công",
                            ServiceId = 3,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 4,
                            AppointmentDate = new DateTime(2026, 4, 1, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1443),
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1482),
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DentistId = "5",
                            EndTime = new TimeSpan(0, 15, 0, 0, 0),
                            PatientId = 4,
                            PatientName = "Phạm Thị Dung",
                            ServiceId = 4,
                            StartTime = new TimeSpan(0, 14, 0, 0, 0),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 5,
                            AppointmentDate = new DateTime(2026, 4, 2, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1443),
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1484),
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DentistId = "2",
                            EndTime = new TimeSpan(0, 10, 30, 0, 0),
                            PatientId = 5,
                            PatientName = "Hoàng Văn Em",
                            ServiceId = 5,
                            StartTime = new TimeSpan(0, 9, 0, 0, 0),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 6,
                            AppointmentDate = new DateTime(2026, 4, 2, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1443),
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1486),
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DentistId = "3",
                            EndTime = new TimeSpan(0, 16, 0, 0, 0),
                            PatientId = 6,
                            PatientName = "Vũ Thị Hương",
                            ServiceId = 6,
                            StartTime = new TimeSpan(0, 15, 0, 0, 0),
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 7,
                            AppointmentDate = new DateTime(2026, 4, 3, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1443),
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1489),
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DentistId = "4",
                            EndTime = new TimeSpan(0, 12, 0, 0, 0),
                            PatientId = 7,
                            PatientName = "Đặng Văn Ích",
                            ServiceId = 7,
                            StartTime = new TimeSpan(0, 10, 0, 0, 0),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 8,
                            AppointmentDate = new DateTime(2026, 4, 4, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1443),
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1493),
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DentistId = "5",
                            EndTime = new TimeSpan(0, 13, 30, 0, 0),
                            PatientId = 8,
                            PatientName = "Ngô Thị Khánh",
                            ServiceId = 8,
                            StartTime = new TimeSpan(0, 13, 0, 0, 0),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 9,
                            AppointmentDate = new DateTime(2026, 4, 4, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1443),
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1496),
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DentistId = "2",
                            EndTime = new TimeSpan(0, 16, 45, 0, 0),
                            PatientId = 9,
                            PatientName = "Tạ Văn Lâm",
                            ServiceId = 9,
                            StartTime = new TimeSpan(0, 16, 0, 0, 0),
                            Status = "Scheduled"
                        },
                        new
                        {
                            Id = 10,
                            AppointmentDate = new DateTime(2026, 4, 5, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1443),
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1498),
                            CreatedBy = "System",
                            CreatedByUserId = "1",
                            DentistId = "3",
                            EndTime = new TimeSpan(0, 12, 30, 0, 0),
                            PatientId = 10,
                            PatientName = "Dương Thị Mộng",
                            ServiceId = 10,
                            StartTime = new TimeSpan(0, 11, 0, 0, 0),
                            Status = "Scheduled"
                        });
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.DentalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DentistId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Diagnosis")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<string>("Prescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("TreatmentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("TreatmentNotes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TreatmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DentistId");

                    b.HasIndex("PatientId");

                    b.ToTable("DentalRecords");
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Allergies")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Gender")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("MedicalHistory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Đường ABC, Quận 1, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1402),
                            DateOfBirth = new DateOnly(1990, 1, 15),
                            Email = "an.nguyen@example.com",
                            FullName = "Nguyễn Văn An",
                            Gender = "Nam",
                            IsActive = true,
                            PhoneNumber = "0901234567"
                        },
                        new
                        {
                            Id = 2,
                            Address = "456 Đường XYZ, Quận 2, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1405),
                            DateOfBirth = new DateOnly(1992, 5, 20),
                            Email = "bich.tran@example.com",
                            FullName = "Trần Thị Bích",
                            Gender = "Nữ",
                            IsActive = true,
                            PhoneNumber = "0902345678"
                        },
                        new
                        {
                            Id = 3,
                            Address = "789 Đường MNO, Quận 3, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1408),
                            DateOfBirth = new DateOnly(1988, 3, 10),
                            Email = "cong.le@example.com",
                            FullName = "Lê Văn Công",
                            Gender = "Nam",
                            IsActive = true,
                            PhoneNumber = "0903456789"
                        },
                        new
                        {
                            Id = 4,
                            Address = "321 Đường PQR, Quận 4, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1410),
                            DateOfBirth = new DateOnly(1995, 7, 25),
                            Email = "dung.pham@example.com",
                            FullName = "Phạm Thị Dung",
                            Gender = "Nữ",
                            IsActive = true,
                            PhoneNumber = "0904567890"
                        },
                        new
                        {
                            Id = 5,
                            Address = "654 Đường STU, Quận 5, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1412),
                            DateOfBirth = new DateOnly(1991, 9, 8),
                            Email = "em.hoang@example.com",
                            FullName = "Hoàng Văn Em",
                            Gender = "Nam",
                            IsActive = true,
                            PhoneNumber = "0905678901"
                        },
                        new
                        {
                            Id = 6,
                            Address = "987 Đường VWX, Quận 6, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1417),
                            DateOfBirth = new DateOnly(1993, 11, 12),
                            Email = "huong.vu@example.com",
                            FullName = "Vũ Thị Hương",
                            Gender = "Nữ",
                            IsActive = true,
                            PhoneNumber = "0906789012"
                        },
                        new
                        {
                            Id = 7,
                            Address = "147 Đường YZA, Quận 7, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1419),
                            DateOfBirth = new DateOnly(1989, 2, 18),
                            Email = "ich.dang@example.com",
                            FullName = "Đặng Văn Ích",
                            Gender = "Nam",
                            IsActive = true,
                            PhoneNumber = "0907890123"
                        },
                        new
                        {
                            Id = 8,
                            Address = "258 Đường BCD, Quận 8, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1422),
                            DateOfBirth = new DateOnly(1996, 4, 30),
                            Email = "khanh.ngo@example.com",
                            FullName = "Ngô Thị Khánh",
                            Gender = "Nữ",
                            IsActive = true,
                            PhoneNumber = "0908901234"
                        },
                        new
                        {
                            Id = 9,
                            Address = "369 Đường EFG, Quận 9, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1425),
                            DateOfBirth = new DateOnly(1987, 6, 5),
                            Email = "lam.ta@example.com",
                            FullName = "Tạ Văn Lâm",
                            Gender = "Nam",
                            IsActive = true,
                            PhoneNumber = "0909012345"
                        },
                        new
                        {
                            Id = 10,
                            Address = "741 Đường HIJ, Quận 10, TP.HCM",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1427),
                            DateOfBirth = new DateOnly(1994, 8, 22),
                            Email = "mong.duong@example.com",
                            FullName = "Dương Thị Mộng",
                            Gender = "Nữ",
                            IsActive = true,
                            PhoneNumber = "0900123456"
                        });
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.PaymentTransaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("AppointmentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MoMoTransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PayUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QrCodeUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RequestId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TransactionId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AppointmentId");

                    b.ToTable("PaymentTransactions");
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.Service", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("DurationMinutes")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Khám",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1327),
                            CreatedBy = "1",
                            Description = "Kiểm tra toàn bộ răng và nướu",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Khám nha",
                            Price = 150000m
                        },
                        new
                        {
                            Id = 2,
                            Category = "Làm sạch",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1329),
                            CreatedBy = "1",
                            Description = "Lấy cao răng và vệ sinh toàn bộ",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Vệ sinh răng",
                            Price = 300000m
                        },
                        new
                        {
                            Id = 3,
                            Category = "Điều trị",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1332),
                            CreatedBy = "1",
                            Description = "Trám sâu răng với vật liệu composite",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Trám răng",
                            Price = 200000m
                        },
                        new
                        {
                            Id = 4,
                            Category = "Điều trị",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1334),
                            CreatedBy = "1",
                            Description = "Nhổ răng hư hỏng nặng",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Nhổ răng",
                            Price = 250000m
                        },
                        new
                        {
                            Id = 5,
                            Category = "Niềng răng",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1336),
                            CreatedBy = "1",
                            Description = "Niềng răng để chỉnh sửa hàm",
                            DurationMinutes = 120,
                            IsActive = true,
                            Name = "Niềng răng",
                            Price = 5000000m
                        },
                        new
                        {
                            Id = 6,
                            Category = "Làm sạch",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1338),
                            CreatedBy = "1",
                            Description = "Tẩy trắng an toàn cho răng",
                            DurationMinutes = 60,
                            IsActive = true,
                            Name = "Tẩy trắng răng",
                            Price = 400000m
                        },
                        new
                        {
                            Id = 7,
                            Category = "Trồng implant",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1340),
                            CreatedBy = "1",
                            Description = "Cấy ghép implant để thay thế răng mất",
                            DurationMinutes = 180,
                            IsActive = true,
                            Name = "Nhân tạo implant",
                            Price = 10000000m
                        },
                        new
                        {
                            Id = 8,
                            Category = "Làm sạch",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1342),
                            CreatedBy = "1",
                            Description = "Tiêm botox chuyên biệt cho nướu",
                            DurationMinutes = 30,
                            IsActive = true,
                            Name = "Tiêm botox nướu",
                            Price = 350000m
                        },
                        new
                        {
                            Id = 9,
                            Category = "Điều trị",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1344),
                            CreatedBy = "1",
                            Description = "Điều trị viêm nướu và chảy máu",
                            DurationMinutes = 45,
                            IsActive = true,
                            Name = "Xử lý viêm nướu",
                            Price = 250000m
                        },
                        new
                        {
                            Id = 10,
                            Category = "Điều trị",
                            CreatedAt = new DateTime(2026, 3, 30, 17, 55, 24, 326, DateTimeKind.Local).AddTicks(1346),
                            CreatedBy = "1",
                            Description = "Bọc sứ để phục hình răng hỏng",
                            DurationMinutes = 90,
                            IsActive = true,
                            Name = "Bọc sứ răng",
                            Price = 800000m
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.HasOne("MyMvcApp.Areas.Admin.Models.ApplicationUser", null)
                        .WithMany("Roles")
                        .HasForeignKey("ApplicationUserId");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("MyMvcApp.Areas.Admin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("MyMvcApp.Areas.Admin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Areas.Admin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("MyMvcApp.Areas.Admin.Models.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.Activity", b =>
                {
                    b.HasOne("MyMvcApp.Areas.Admin.Models.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.Appointment", b =>
                {
                    b.HasOne("MyMvcApp.Areas.Admin.Models.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Areas.Admin.Models.ApplicationUser", "Dentist")
                        .WithMany()
                        .HasForeignKey("DentistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Areas.Admin.Models.Patient", "Patient")
                        .WithMany("Appointments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Areas.Admin.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CreatedByUser");

                    b.Navigation("Dentist");

                    b.Navigation("Patient");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.DentalRecord", b =>
                {
                    b.HasOne("MyMvcApp.Areas.Admin.Models.ApplicationUser", "Dentist")
                        .WithMany()
                        .HasForeignKey("DentistId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Areas.Admin.Models.Patient", "Patient")
                        .WithMany("DentalRecords")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Dentist");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.Payment", b =>
                {
                    b.HasOne("MyMvcApp.Areas.Admin.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Areas.Admin.Models.Patient", "Patient")
                        .WithMany("Payments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("MyMvcApp.Areas.Admin.Models.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Appointment");

                    b.Navigation("Patient");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.PaymentTransaction", b =>
                {
                    b.HasOne("MyMvcApp.Areas.Admin.Models.Appointment", "Appointment")
                        .WithMany()
                        .HasForeignKey("AppointmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Appointment");
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.ApplicationUser", b =>
                {
                    b.Navigation("Roles");
                });

            modelBuilder.Entity("MyMvcApp.Areas.Admin.Models.Patient", b =>
                {
                    b.Navigation("Appointments");

                    b.Navigation("DentalRecords");

                    b.Navigation("Payments");
                });
#pragma warning restore 612, 618
        }
    }
}
